# Generated by Django 4.0.3 on 2023-02-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_animal_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(default=False, upload_to='pets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
