# Generated by Django 4.0.3 on 2023-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_foto_alter_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
